### ISSUE TITLE
This is personal 

### ISSUE THREAD

**Issue by ReflectedEight5** [Vetrnn/TheCollectiveGaming-Github#2]
Tim: idk ReflectedEight5, Someone you prob dont like at the moment, hopefully this makes you change your mind:
idk all this stuff but im going to make it simple but not quick, i do want to apoligize first of all, being an asshole is being an asshole :D, but for real:
2020 was a bad year for everyone, and specially me, ngl 2020 got harder and harder by time. 
I did not treat people well, but i think that i have aproved and became a nicer person, i dont like blaming stuff, but it was night basically all the time.
I feel like im more mature, i try to be the best i can att the moment and time, i do miss also getting pinged so, if this dont go threw then i want to get the notifications atleast.
the thing i really miss is playing with you gys, if its talking or not, hehe your welcome for the sub mister god himself?, boosting your ego :D, hope thos was enough: Tim Jönsson
form his motherland, Sweden at 1.33 am wtf which = late as fuck, ask for credit card number and ill give it :D
kind of a sloppy text

**Comment by Vetrnn** [comment]
Ok Tim, a couple of things. Before I get into it, I would like to say that both me and Dad talked about this and came to a conclusion. So this is by no means bias.

I hoped that you would have been a bit more serious about this appeal, as if it truly matters to you, you would have given more. Also I would like to add that making a ban appeal at 1.33 am isn't a good idea, just shows to me that you don't really care much. Making it in a whole 3 minutes does not prove me anything, it just pushing you further and further away from an unban. 

2020 was indeed a bad year. For everybody. But that does not give you the right to say the stuff you did, to both me and Noa. I have told you a million times that those things are not jokes, I have warned you a million times, yet you kept going. I think you are old enough to control your own emotions, just like everybody does. Things like making fun of somebody's past (parents), is unacceptable. And that shit sticks with me, because that is a person your talking about, and I don't see it as a joke. There is a fine line between a joke and a insult, I hope you will be able to see that in the future.

To end this, I will sadly reject your ban appeal. I believe it is to soon to unban you when you dont even take your appeals seriously. That is the least you can do to prove to me and Noa that you have matured. Maybe in the future things will be different, but for now, it will be a no.

Not the god himself, just a person mature enough to have self respect,
Vet

**Comment by ReflectedEight5** [comment]
i respect it, but i dont like you lying, yet you kept going. I think you are old enough to control your own emotions, just like everybody does. Things like making fun of somebody's past (parents), never in my life have i ever made fun of Noa's parents, the only thing i have done is ask what happened and i never got an answear and i respect that, and i dont know what else to say, if me getting more mature and ive changed a lot isn't a good enough thing then i dont know what- Tim

**Comment by ReflectedEight5** [comment]
Never in my life has i made jokes about Noa's parents, and i feel bad for him, i have never made a joke about his dead parents, in my fucking life, im sorry im getting not mad but, ok more im so serious about, that i have never joked about his dead parents

**Comment by ReflectedEight5** [comment]
anyways can i atleast join the discord server so i can get notifications when the streams come out, last i will say here: Tim

**Comment by ReflectedEight5** [comment]
im ngl, i will bet my life i have not made a joke about his parents, and im serious
