### ISSUE TITLE
actually kill me 

### ISSUE THREAD

**Issue by ReflectedEight5** [Vetrnn/TheCollectiveGaming-Github#5]
this is even worse day, to make this happen, i wont do anything about it this appeal, my brother got hit by a car today at 45 km per hour swedish km, he has just got a A-C broken Spine and got a lot of not life threat'ning idk how to say it in swedish conditions, just info from me today, im sorry you dont need to know this, you hate me anyways, gb 4 ever than, just plss dont block me Noa.

**Comment by ReflectedEight5** [comment]
if he dies i will kill myself this time 
there wont be anything to stop me

**Comment by Alexabawesome** [comment]
Im sorry but this is not acceptable behavior. I can confidently say for the whole mod team and TCG that we don't take talking about killing one's self lightly. This is manipulative behavior and it's not ok. I personally do not find this funny or at all ok and it will stop right this instance. You will no longer interact with anyone of the TCG from this point on, as you are being manipulative, rude, and upsetting to everyone.

Even if I believed everything you said, I really can't stand the need to trauma dump in a public forum space about personal matters. You having a bad day does not excuse the things you have done or the words you have said and they never will. Your trauma does not give me any reason to give you a special pass or "another chance".

You will never be allowed back into the discord or the stream, and because you are banned you wouldn't be watching the streams either. You are not a safe person to have in this community and we want nothing to do with you and your presence

-Alexa

**Comment by ReflectedEight5** [comment]
i couldnt give anymore fucks anymore 
gb
